#!/usr/bin/env bash

# Change the working directory to Replicator.
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

mvn exec:java -q -Dexec.mainClass="com.scylladb.cdc.replicator.Main" -Dexec.args="$*" -Djava.util.logging.config.file="src/main/resources/logging.properties"
