#release configuration
#Sat Jun 21 16:55:44 AST 2025
completedPhase=generate-release-poms
exec.additionalArguments=-Dgpg.passphrase\=
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.scylladb\:scylla-cdc=1.3.7-SNAPSHOT
project.dev.com.scylladb\:scylla-cdc-base=1.3.7-SNAPSHOT
project.dev.com.scylladb\:scylla-cdc-driver3=1.3.7-SNAPSHOT
project.dev.com.scylladb\:scylla-cdc-lib=1.3.7-SNAPSHOT
project.rel.com.scylladb\:scylla-cdc=1.3.6
project.rel.com.scylladb\:scylla-cdc-base=1.3.6
project.rel.com.scylladb\:scylla-cdc-driver3=1.3.6
project.rel.com.scylladb\:scylla-cdc-lib=1.3.6
project.scm.com.scylladb\:scylla-cdc-base.empty=true
project.scm.com.scylladb\:scylla-cdc-driver3.empty=true
project.scm.com.scylladb\:scylla-cdc-lib.empty=true
project.scm.com.scylladb\:scylla-cdc.connection=scm\:git\:https\://github.com/scylladb/scylla-cdc-java
project.scm.com.scylladb\:scylla-cdc.developerConnection=scm\:git\:https\://github.com/scylladb/scylla-cdc-java
project.scm.com.scylladb\:scylla-cdc.tag=HEAD
project.scm.com.scylladb\:scylla-cdc.url=https\://github.com/scylladb/scylla-cdc-java
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=scylla-cdc-1.3.6
scm.tagNameFormat=scylla-cdc-@{project.version}
scm.url=scm\:git\:https\://github.com/scylladb/scylla-cdc-java
