#!/usr/bin/env bash

# Change the working directory to Printer.
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

mvn exec:java -q -Dexec.mainClass="com.scylladb.cdc.printer.Main" -Dexec.args="$*" -Djava.util.logging.config.file="src/main/resources/logging.properties" -Dexec.cleanupDaemonThreads=false
